repos:
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--profile, black]
- repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
  rev: v0.4.5
  hooks:
      # Run the linter.
  - id: ruff
    args: [--fix]
      # Run the formatter.
  - id: ruff-format
- repo: https://github.com/iterative/dvc
  rev: 3.38.0
  hooks:
  - id: dvc-pre-commit
    language_version: python3
    stages:
    - commit
  - id: dvc-pre-push
    additional_dependencies: ['.[gs]']
    language_version: python3
    stages:
    - push
  - id: dvc-post-checkout
    language_version: python3
    stages:
    - post-checkout
    always_run: true
