stages:
  wayland:
    cmd: llm_learning --llm-model ${llm_model} data/raw/Wayland-MA.pdf
    params:
    - llm_model
    deps:
    - data/raw/Wayland-MA.pdf
    - llm_learning/analyze.py
    outs:
    - data/processed/Wayland-MA-goals.csv
    - data/processed/Wayland-MA-actions.csv
    - data/processed/Wayland-MA.json
    - dvclive/Wayland-MA
  ashland:
    cmd: llm_learning --llm-model ${llm_model} data/raw/Ashland-MA.pdf
    params:
    - llm_model
    deps:
    - data/raw/Ashland-MA.pdf
    - llm_learning/analyze.py
    outs:
    - data/processed/Ashland-MA-goals.csv
    - data/processed/Ashland-MA-actions.csv
    - data/processed/Ashland-MA.json
    - dvclive/metrics/Ashland-MA
  melrose:
    cmd: llm_learning --llm-model ${llm_model} data/raw/Melrose-MA.pdf
    params:
    - llm_model
    deps:
    - data/raw/Melrose-MA.pdf
    - llm_learning/analyze.py
    outs:
    - data/processed/Melrose-MA-goals.csv
    - data/processed/Melrose-MA-actions.csv
    - data/processed/Melrose-MA.json
    - dvclive/metrics/Melrose-MA
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
