stages:

  download_dracula:
    cmd: curl https://www.gutenberg.org/files/345/345-0.txt --output data/external/dracula.txt
    outs:
    - data/external/dracula.txt
  download_frankenstein:
    cmd: curl https://www.gutenberg.org/cache/epub/42324/pg42324.txt --output data/external/frankenstein.txt
    outs:
    - data/external/frankenstein.txt
  download_jane_eyre:
    cmd: curl https://www.gutenberg.org/files/1260/1260-0.txt --output data/external/jane_eyre.txt
    outs:
    - data/external/jane_eyre.txt
  run_analysis:
    cmd: python llm_learning/run_analysis.py data/external data/processed
    deps:
    - llm_learning/run_analysis.py
    - data/external/dracula.txt
    - data/external/frankenstein.txt
    - data/external/jane_eyre.txt
    outs:
    - data/processed/raw_counts/
    - data/processed/summary.csv



