stages:
  wayland:
    cmd: llm_learning --llm-model ${llm_model} --context-length ${context_length}
      data/raw/Wayland-MA.pdf
    params:
    - llm_model
    deps:
    - data/raw/Wayland-MA.pdf
    - llm_learning/analyze.py
    outs:
    - data/processed/Wayland-MA-goals.csv
    - data/processed/Wayland-MA-actions.csv
    - data/processed/Wayland-MA.json
    - dvclive/plots/metrics/Wayland-MA
  ashland:
    cmd: llm_learning --llm-model ${llm_model} --context-length ${context_length}
      data/raw/Ashland-MA.pdf
    params:
    - llm_model
    deps:
    - data/raw/Ashland-MA.pdf
    - llm_learning/analyze.py
    outs:
    - data/processed/Ashland-MA-goals.csv
    - data/processed/Ashland-MA-actions.csv
    - data/processed/Ashland-MA.json
    - dvclive/plots/metrics/Ashland-MA
  melrose:
    cmd: llm_learning --llm-model ${llm_model} --context-length ${context_length}
      data/raw/Melrose-MA.pdf
    params:
    - llm_model
    deps:
    - data/raw/Melrose-MA.pdf
    - llm_learning/analyze.py
    outs:
    - data/processed/Melrose-MA-goals.csv
    - data/processed/Melrose-MA-actions.csv
    - data/processed/Melrose-MA.json
    - dvclive/plots/metrics/Melrose-MA
  towns:
    foreach:
    - Boston-MA
    - Acton-MA
    - Amherst-MA
    - Arlington-MA
    - Brookline-MA
    - Burlington-VT
    - Cambridge-MA
    - Concord-MA
    - Dedham-MA
    - Gloucester-MA
    - Harvard-MA
    - Lincoln-MA
    - Medford-MA
    - Natick-MA
    - Wellesley-MA
    - Weston-MA
    do:
      cmd: llm_learning --llm-model ${llm_model} --context-length ${context_length}
        data/raw/${item}.pdf
      params:
      - llm_model
      deps:
      - data/raw/${item}.pdf
      - llm_learning/analyze.py
      outs:
      - data/processed/${item}-goals.csv
      - data/processed/${item}-actions.csv
      - data/processed/${item}.json
      - dvclive/plots/metrics/${item}
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
