stages:
  towns:
    foreach:
    - Boston-MA
    - Acton-MA
    - Amherst-MA
    - Arlington-MA
    - Ashland-MA
    - Brookline-MA
    - Burlington-VT
    - Cambridge-MA
    - Concord-MA
    - Dedham-MA
    - Gloucester-MA
    - Harvard-MA
    - Lincoln-MA
    - Medford-MA
    - Melrose-MA
    - Natick-MA
    - Wayland-MA
    - Wellesley-MA
    - Weston-MA
    do:
      cmd: llm_learning --llm-model ${llm_model} --context-length ${context_length}
        data/raw/${item}.pdf
      params:
      - llm_model
      deps:
      - data/raw/${item}.pdf
      outs:
      - data/processed/${item}-goals.csv
      - data/processed/${item}-actions.csv
      - data/processed/${item}.json
      - metrics/${item}/
metrics:
- metrics/Boston-MA/metrics.json
- metrics/Acton-MA/metrics.json
- metrics/Amherst-MA/metrics.json
- metrics/Arlington-MA/metrics.json
- metrics/Ashland-MA/metrics.json
plots:
- metrics/Boston-MA/plots/metrics:
    x: step
- metrics/Acton-MA/plots/metrics:
    x: step
- metrics/Amherst-MA/plots/metrics:
    x: step
- metrics/Arlington-MA/plots/metrics:
    x: step
- metrics/Ashland-MA/plots/metrics:
    x: step
